# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s= "Hi there Sam!"
x = s.split()
print(x)

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [13]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [16]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
import numpy as np
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [19]:
import numpy as np
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
import numpy as np
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [35]:
import pandas as pd
d={"ID":[300,400,500],"NAME": ["SAFRIN","NIHAR","YAZRIN"]}
df=pd.DataFrame(d)
df

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
date_series = pd.Series(pd.date_range("01-01-2023","10-02-2021"))
date_series

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [32]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [33]:
list1=zip(lists)
df=pd.DataFrame(list1)
df

              0
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]